// swift-tools-version: 6.0
import PackageDescription

let package = Package(
    name: "SwiftTestHarness",
    platforms: [
        .macOS(.v14)
    ],
    dependencies: [
        .package(name: "Ed25519Dalek", path: "../build/SPMPackage/macosArm64/Debug")
    ],
    targets: [
        .testTarget(
            name: "SwiftTestHarnessTests",
            dependencies: [
                .product(name: "Ed25519DalekLibrary", package: "Ed25519Dalek")
            ],
            swiftSettings: [
                .unsafeFlags([
                    "-F", "/Library/Developer/CommandLineTools/Library/Developer/Frameworks",
                ]),
            ],
            linkerSettings: [
                // The SPM package generated by Kotlin's embedSwiftExportForXcode
                // task contains Swift wrapper sources and C bridge declarations,
                // but the actual symbol implementations
                // (`__root____getExceptionMessage__...`) live in
                // `libEd25519Dalek.a` produced by the
                // `linkSwiftExportBinaryDebugStaticMacosArm64` /
                // `mergeMacosDebugSwiftExportLibraries` chain. Xcode wires
                // that archive into its own link step via
                // BUILT_PRODUCTS_DIR; a standalone `swift test` invocation
                // has to point at it explicitly. The archive lands at
                // `<repo>/build/swift-test/libEd25519Dalek.a` when the
                // embed task runs with the macOS Xcode-style environment
                // variables (see .github/workflows/swift.yml).
                .unsafeFlags([
                    "-L", "../build/swift-test",
                    "-lEd25519Dalek",
                    "-F", "/Library/Developer/CommandLineTools/Library/Developer/Frameworks",
                    "-Xlinker", "-rpath", "-Xlinker", "/Library/Developer/CommandLineTools/Library/Developer/Frameworks",
                    "-Xlinker", "-rpath", "-Xlinker", "/Library/Developer/CommandLineTools/Library/Developer/usr/lib",
                ]),
            ]
        ),
    ]
)
